### ISSUE TITLE
Честность лотереи

### ISSUE THREAD

**Issue by arvkonstantin** [tonlab-pro-team/fortuna-contracts#2]
Добрый день, хотел уточнить по поводу честности лотереи, на официальном сайте TON есть статья https://docs.ton.org/ko/develop/smart-contracts/guidelines/random-number-generation
В ней говорится о том, что на random недьзя полагаться в смартконтрактах, что валидатор может сгенерировать удобное для себя случайно число.

**Comment by 1IxI1** [comment]
В статье не говорится, что _нельзя полагаться_ на рандомайзеры в контрактах. Там лишь пишут о том, что даже самые надежные методы _не на 100% защищены_ от злоумышленников. Остается только поразмышлять: какой валидатор со стейком в 300k TON будет пробовать заниматься подтасовкой тиражной лотереи, если даже решившись на подобное, ему было бы куда выгоднее и проще мухлевать с мгновенными? Тем ещё более, что розыгрыш данной лотереи может быть запущен **любым отправителем**, что придает децентрализации и честности процессу ([lottery.fc:189](https://github.com/tonlab-pro-team/fortuna-contracts/blob/main/contracts/lottery.fc#L189-L196)):
```rust
    if (op == 0) {
        if (equal_slices(sender_address, operator_address)) {
            return (); ;; topup
        }

        throw_if(401, draw_time == 0); ;; lottery is not active

        if (now() >= draw_time) { ;; try drawing a lottery
             ...
```
